Python3: unicodify subprocess stdout
Fix the following error:
```
File "/home/travis/build/galaxyproject/planemo/planemo/database/postgres.py", line 27, in list_databases
    identifiers.append(line.split("|")[0].strip())
TypeError: 'str' does not support the buffer interface