update pin of gxformat2
seems that the latest version breaks planemo

```
Traceback (most recent call last):
  File "/home/runner/.local/bin/planemo", line 4, in <module>
    from planemo.cli import planemo
  File "/home/runner/.local/share/uv/tools/planemo/lib/python3.10/site-packages/planemo/cli.py", line 25, in <module>
    from planemo.galaxy import profiles
  File "/home/runner/.local/share/uv/tools/planemo/lib/python3.10/site-packages/planemo/galaxy/__init__.py", line 3, in <module>
    from .config import galaxy_config
  File "/home/runner/.local/share/uv/tools/planemo/lib/python3.10/site-packages/planemo/galaxy/config.py", line 48, in <module>
    from planemo.galaxy.workflows import (
  File "/home/runner/.local/share/uv/tools/planemo/lib/python3.10/site-packages/planemo/galaxy/workflows.py", line 34, in <module>
    from gxformat2.interface import (
ModuleNotFoundError: No module named 'gxformat2.interface'
```

using the same as in the galaxy pinned requirements